### ISSUE TITLE
Dislocation when project has a custom .editorconfig

### ISSUE THREAD

**Issue by ClassicOldSong** [pd4d10/octohint#1]
Such as this https://github.com/ClassicOldSong/KarasamaEgg/blob/master/src/main.js
All hints displays to the wring position which could be confusing.
![image](https://cloud.githubusercontent.com/assets/10512422/25015198/74195048-20ad-11e7-8900-f60f9fcd591d.png)

**Comment by pd4d10** [comment]
Thanks for your report! Fixed in v1.1.0.

New version has been published to Chrome web store. Will be available soon.
