### ISSUE TITLE
This plugin causes the displacement of line-toolbar

### ISSUE THREAD

**Issue by ClassicOldSong** [pd4d10/octohint#10]
![image](https://user-images.githubusercontent.com/10512422/33368848-68678cc8-d4b8-11e7-8d71-307a74dfe234.png)
As shown in the picture, I'm selecting line 1 but the toolbar appears in the wrong place.

**Comment by pd4d10** [comment]
@ClassicOldSong Thanks! Could you please provide the URL?

**Comment by ClassicOldSong** [comment]
https://github.com/pd4d10/octohint/blob/master/scripts/get-lib-names.js#L5
Like this, when first open the toolbar is at the right place, then  you click on some other line numbers and you'll find that the toolbar appears wrongly.

**Comment by pd4d10** [comment]
@ClassicOldSong The latest version should fix this. Thanks for your report.

**Comment by ClassicOldSong** [comment]
@pd4d10 Thanks a lot for making this awesome plugin!
