### ISSUE TITLE
Opera extension

### ISSUE THREAD

**Issue by jaggs6** [pd4d10/octohint#12]
Would be great if someone created an Opera extension

**Comment by pd4d10** [comment]
@jaggs6 Actually I've tried to submit it to opera extensions store, but their reviewer seems don't understand what is this extension used for and reject it.

Have you tried this?

https://addons.opera.com/en/extensions/details/download-chrome-extension-9/

Or you can try [manual install](https://github.com/pd4d10/octohint#chrome) it

Thanks!

**Comment by pd4d10** [comment]
@jaggs6 Installation of Opera browser updated, see [here](https://github.com/pd4d10/octohint#installation).

If you have any other questions, feel free to reopen it.

Thanks!
