### ISSUE TITLE
Firefox installation error - options_page

### ISSUE THREAD

**Issue by OranShuster** [pd4d10/octohint#13]
Cannot install 2.0.1 on FF57 or FF58 (beta) 
installing the addon in debug mode shows the following error
`Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.`

there is options_ui which is compatible with firefox but it appears that it will not accept the options_page entry

**Comment by pd4d10** [comment]
`options_page` is for old version Chrome compatibility, see:

https://developer.chrome.com/extensions/optionsV2#migration

Firefox will show this warning, but you can still use it.

Maybe we can release a different zip for Firefox to remove this warning later.

Thanks!
