### ISSUE TITLE
Sentry library usage in source code

### ISSUE THREAD

**Issue by matelakat** [pd4d10/octohint#14]
Hi,

I came across your project and it seems to be quite useful for me. One thing that worries me is when I was looking at the source code I found:

https://github.com/pd4d10/octohint/blob/master/src/sentry.ts

Does that mean that sentry is being used for catching bugs that might happen while running the client in my browser? If so, what information is being sent over to sentry and in what circumstances?

Thanks,
Mate

**Comment by pd4d10** [comment]
> Does that mean that sentry is being used for catching bugs that might happen while running the client in my browser?

Yes, uncaught JS errors will be sent to sentry.io server

> What information is being sent over to sentry and in what circumstances?

In my opinion something like error stacks, browser version and OS version will be sent to server. It is sure that **your code will not be uploaded**, as I said at [Introduction at Medium](https://medium.com/@pd4d10/introducing-octohint-e1a3e4b80c47).

I understand your concerns. I'll add a chapter of build instruction to README later, then you can remove this sentry client and build it yourself for local use.

Thanks!

**Comment by matelakat** [comment]
Hi @pd4d10 

Thank you for your quick answer! For me sending anything out from such client-side plugins without user approval to a third party (even if that's a well-trusted sentry) is a big no, so unfortunately I need to live my life without this rather useful plugin. I think moving the sentry integration to an optional feature - like usage statistics and error reporting is done in other software - would be the way to go.

Thanks,
Mate

**Comment by pd4d10** [comment]
Thanks for your good suggestion! I'll consider adding an option to let user disable it.

I'm going to close this. If you have any other questions, feel free to reopen it :)

**Comment by pd4d10** [comment]
@matelakat  Error report related codes are removed in latest v2.0.3
