### ISSUE TITLE
Update Firefox installation instructions?

### ISSUE THREAD

**Issue by markerikson** [pd4d10/octohint#18]
The Firefox installation instructions currently say:

> Make sure your version of Firefox supports web extensions. The installation is the same as Manual installation of Chrome.

The Chrome instructions, in turn, say:

> Go to release page, find chrome.zip file, download and unpack it.

I'm currently running Firefox 57.  I've tried unzipping the `chrome.zip` file.  I then went to Firefox's Addons Manager screen and selected "Install Addon from File".  If I select the `chrome.zip` file directly, or select the unpacked `manifest.json` file, Firefox says "This addon could not be installed because it appears to be corrupt".  I also tried copying the unpacked folder to my profile's `extensions` folder and restarting Firefox, with no success.

I'd appreciate updated instructions for installing the addon in Firefox.

**Comment by pd4d10** [comment]
@markerikson I find this link:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox

It seems that you should go to `about:debugging` instead of `about:addons`. I'll update README for Firefox installation, thanks!

**Comment by markerikson** [comment]
Thanks. That seems to have gotten it to load and seem to work, although `about:debugging` does show this warning:

> Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

**Comment by pd4d10** [comment]
@markerikson

> Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

This is a legacy field for old version Chrome, see #13
