### ISSUE TITLE
Highlight position wrong if code is written with tabs

### ISSUE THREAD

**Issue by hendrysadrak** [pd4d10/octohint#19]
On the following image i have highlit `MAX_INT32`. As you can see the highlight is shifted a bit left of where it should be. 

File: https://github.com/sindresorhus/park-miller/blob/master/index.js

![image](https://user-images.githubusercontent.com/4000963/34983572-b3bb9010-fab6-11e7-9c80-5c68fb0efec3.png)
 
Chrome Version 65.0.3315.3 (Official Build) dev (64-bit)
MacOS 10.13.3
Display pixelRatio 2

**Comment by hendrysadrak** [comment]
And in this image i have highlit `this`

![image](https://user-images.githubusercontent.com/4000963/34983747-314f1c0e-fab7-11e7-977c-8076a116b404.png)

**Comment by pd4d10** [comment]
@hendrysadrak Thanks for you report!

It has been already fixed at https://github.com/pd4d10/octohint/commit/177900656fc780555a633ab66f5cd251a4991cc1. I'll publish a new version ASAP.

**Comment by pd4d10** [comment]
Fixed at v2.0.2
