### ISSUE TITLE
feature request: safari support

### ISSUE THREAD

**Issue by notgiorgi** [pd4d10/octohint#2]

**Comment by pd4d10** [comment]
Thanks for your recommendation.

IntelliOcto's code IntelliSense feature is powered by TypeScript language service. This bundle size is a little large(2M+ after uglify), so it may take some time to execute it for browsers.

For Chrome, this bundle will only execute once as background script when extension loaded. Content script only need to get position of mouse click or hover, communicate with background script, and render DOM.

I'm not sure if Safari extensions support background script like Chrome extension's. If not, this large bundle need to be executed every time on page loaded, it could be very slow.

I'll do some research on it. Also, pull request is very welcome.

**Comment by pd4d10** [comment]
@notgiorgi 
v1.3.0 already has support Safari. Thanks for you suggestion!
Guide here: https://github.com/pd4d10/intelli-octo#safari
