### ISSUE TITLE
Visual Studio Online Support

### ISSUE THREAD

**Issue by FizzBuzz791** [pd4d10/octohint#20]
Firstly, amazing product and would have been super useful at my previous job (although still very useful in my free time). My current job uses Visual Studio Online though and this would be incredibly handy to have if it's possible to add support.

**Comment by pd4d10** [comment]
@FizzBuzz791 Do you mean [Visual Studio Team Services](https://www.visualstudio.com/team-services/)? I tried it and it seems already have a builtin IntelliSense support

**Comment by FizzBuzz791** [comment]
Yeah. It kind of does. Only when reviewing the raw files though, not in pull requests.

**Comment by pd4d10** [comment]
@FizzBuzz791  Got it. Octohint also doesn't support pull requests currently, see #9 . Still need do some research on it :)

Thanks for your report!
