### ISSUE TITLE
On a private Github installation, fails to load font...

### ISSUE THREAD

**Issue by sapirgolan** [pd4d10/octohint#22]
Hi,

I'm working in an organization that has a private installation of github.
The extension fails to load due to the following error:
_Refused to load the font '<URL>' because it violates the following Content Security Policy directive: `"font-src assets.github.corp.****.com"`_  
(full domain name was removed for privacy)
There is no resonse for any of the requests made by the extention.

**Comment by pd4d10** [comment]
@sapirgolan Octohint does not load any custom font, so the `Refused to load the font` error may not be related with it.

Have you given the permission of your site?

https://github.com/pd4d10/octohint/blob/master/README.md#get-your-private-site-works

**Comment by sapirgolan** [comment]
Sure, this was the first thing I did.

**Comment by pd4d10** [comment]
@sapirgolan OK. Debugging is a little complicated:

Please go to

chrome://extensions/?id=hbkpjkfdheainjkkebeoofkpgddnnbpk

and make sure your site is already listed at *permissions*.

Then click **Inspect views -> background page** to open a debugging popup, and refresh your site. Maybe there is some useful information.

The private GitHub's DOM may be different with https://github.com, so our scripts may not be injected correctly.

**Comment by sapirgolan** [comment]
Hi @pd4d10,

I've followed your instructions.
My site is already listed at _permissions_

Bellow you can see the error from the debugging
```Error in event handler for runtime.onMessage: TypeError: Cannot read property '23' of undefined
    at t.getOccurrences (chrome-extension://hbkpjkfdheainjkkebeoofkpgddnnbpk/dist/background.js:1:737573)
    at handleMessage (chrome-extension://hbkpjkfdheainjkkebeoofkpgddnnbpk/dist/background.js:1:730154)
    at chrome-extension://hbkpjkfdheainjkkebeoofkpgddnnbpk/dist/background.js:1:729044```

**Comment by pd4d10** [comment]
@sapirgolan Please provide the full error message

**Comment by pd4d10** [comment]
I'm going to close this since we don't have enough information to figure it out.

Feel free to reopen it :)
