### ISSUE TITLE
Update Readme for firefox users

### ISSUE THREAD

**Issue by linonetwo** [pd4d10/octohint#25]
You can use the "On your own" signing option on [Mozilla addon site](https://addons.mozilla.org/en-US/developers/addon/submit/distribution) to create an addon for your self.
In this way, you don't need to load it as temporary addon every time you restart the Firefox.

**Comment by pd4d10** [comment]
Sounds good. Willing to send a PR?

**Comment by linonetwo** [comment]
Added.
