### ISSUE TITLE
Seems a bug

### ISSUE THREAD

**Issue by pexcn** [pd4d10/octohint#8]
![1](https://user-images.githubusercontent.com/4590439/29249580-f098ac92-8064-11e7-8037-f31ae1da7f6b.png)

**Comment by pd4d10** [comment]
Could you please provide the URL?

**Comment by pexcn** [comment]
https://github.com/pexcn/shadowsocks-windows/blob/master/shadowsocks-csharp/Program.cs#L91-L102

Ctrl + left click the `e` value.

**Comment by pd4d10** [comment]
Will be fixed at next release.

Thanks!

**Comment by pexcn** [comment]
Thanks
